# Place validation for user text input in this file.

# Maps incorrect string input to string with correct spelling. TODO this should be checked when check_ingredients() raises KeyError.
corrections = {
    "Abecean Lonfgin": "Abecean Longfin",
    "Abcean Longifn": "Abecean Longfin",
    "Abceean Longfin": "Abecean Longfin",
    "Abecaen Longfin": "Abecean Longfin",
    "Abecean Longifn": "Abecean Longfin",

    "Alow Vera Leaves": "Aloe Vera Leaves",
    "Alore Vera Leaves": "Aloe Vera Leaves",
    "Aleo Vera Leaves": "Aloe Vera Leaves",
    "Aloe Vrea Leaves": "Aloe Vera Leaves",
    "Aloe Vare Leaves": "Aloe Vera Leaves",
    "Aloe Vera Laves": "Aloe Vera Leaves",
    "Aloe Verra Leaves": "Aloe Vera Leaves",
    "Aloe Vera Laeves": "Aloe Vera Leaves",
    "Aloe Vera Lvaes": "Aloe Vera Leaves",
    "Aloe Vera": "Aloe Vera Leaves",
    "Aloe Vera Lives": "Aloe Vera Leaves",
    "Aloe Vera Levas": "Aloe Vera Leaves",
    "Aloe Vwra Leaves": "Aloe Vera Leaves",

    "Anscestor Moth Wing": "Ancestor Moth Wing",
    "Acnestor Moth Wing": "Ancestor Moth Wing",
    "Ancster Moth Wing": "Ancestor Moth Wing",
    "Ancetsor Moth Wing": "Ancestor Moth Wing",
    "Ancstestor Moth Wing": "Ancestor Moth Wing",
    "Ancsestor Moth Wing": "Ancestor Moth Wing",
    "Amcestor Moth Wing": "Ancestor Moth Wing",
    "Ancestor Moht Wing": "Ancestor Moth Wing",
    "Ancestor Mtoh Wing": "Ancestor Moth Wing",
    "Ancestor Moth Wngi": "Ancestor Moth Wing",

    "Ass Creep Cluster": "Ash Creep Cluster",
    "Ahs Creep Cluster": "Ash Creep Cluster",
    "Ashe Creep Cluster": "Ash Creep Cluster",
    "Ash Crpee Cluster": "Ash Creep Cluster",
    "Ash Cpere Cluster": "Ash Creep Cluster",
    "Ash Crepe Cluster": "Ash Creep Cluster",
    "Ash Creep Clstuer": "Ash Creep Cluster",
    "Ash Creep Clutser": "Ash Creep Cluster",
    "Ash Creep Lcuster": "Ash Creep Cluster",
    "Ash Creep": "Ash Creep Cluster",

    "Ass Hopper Jelly": "Ash Hopper Jelly",
    "Ashe Hopper Jelly": "Ash Hopper Jelly",
    "Ash Hopper": "Ash Hopper Jelly",
    "Hopper Jelly": "Ash Hopper Jelly",
    "Ahs Hopper Jelly": "Ash Hopper Jelly",
    "Ash Hooper Jelly": "Ash Hopper Jelly",
    "Ash Hpooer Jelly": "Ash Hopper Jelly",
    "Ash Hoper Jelly": "Ash Hopper Jelly",
    "Ash Hopper Jlely": "Ash Hopper Jelly",
    "Ash Hopper Jelye": "Ash Hopper Jelly",
    "Ash Hopper Jelyl": "Ash Hopper Jelly",

    "Ashne Grass Pod": "Ashen Grass Pod",
    "Ahsen Grass Pod": "Ashen Grass Pod",
    "Sahen Grass Pod": "Ashen Grass Pod",
    "Ashem Grass Pod": "Ashen Grass Pod",
    "Ashen Garss Pod": "Ashen Grass Pod",
    "Ashen Grsas Pod": "Ashen Grass Pod",
    "Ashen Graas Pod": "Ashen Grass Pod",
    "Ashen Grass Pdo": "Ashen Grass Pod",

    "Brea Claws": "Bear Claws",
    "Bear Claw": "Bear Claws",
    "Bears Claw": "Bear Claws",
    "Bear's Claw": "Bear Claws",
    "Bear's Claws": "Bear Claws",
    "Bare Claws": "Bear Claws",
    "Brae Claws": "Bear Claws",
    "Bae Claws": "Bear Claws",
    "Bear Clsaw": "Bear Claws",
    "Bear Cawls": "Bear Claws",
    "Bear Clwas": "Bear Claws",

    "Beee": "Bee",
    "Ebe": "Bee",

    "Behive Husk": "Beehive Husk",
    "Bheeive Husk": "Beehive Husk",
    "Beehvie Husk": "Beehive Husk",
    "Beehiev Husk": "Beehive Husk",
    "Beehive Hsuk": "Beehive Husk",
    "Beehive Huks": "Beehive Husk",

    "Berits Ashes": "Berit's Ashes",
    "Berit Ashes": "Berit's Ashes",
    "Berit": "Berit's Ashes",
    "Breit's Ashes": "Berit's Ashes",
    "Bert's Ashes": "Berit's Ashes",
    "Berti's Ashes": "Berit's Ashes",
    "Berit's Ahses": "Berit's Ashes",

    "Bleding Crown": "Bleeding Crown",
    "Beleding Crown": "Bleeding Crown",
    "Bldeeing Crown": "Bleeding Crown",
    "Bledeing Crown": "Bleeding Crown",
    "Bleedng Crown": "Bleeding Crown",
    "Bleednig Crown": "Bleeding Crown",
    "Bleeding Crwon": "Bleeding Crown",
    "Bleeding Corn": "Bleeding Crown",
    "Bleeding Cwron": "Bleeding Crown",
    "Bleeding Cworn": "Bleeding Crown",

    "Blisterwory": "Blisterwort",
    "Blsterwort": "Blisterwort",
    "Bilsterwort": "Blisterwort",
    "Blitserwort": "Blisterwort",
    "Blistserwort": "Blisterwort",
    "Blisterwrot": "Blisterwort",
    "Blisterwtor": "Blisterwort",

    "Bule Butterfly Wing": "Blue Butterfly Wing",
    "Blue Btterfliy Wing": "Blue Butterfly Wing",
    "Blue Butterfgly Wing": "Blue Butterfly Wing",
    "Bleu Butterfly Wing": "Blue Butterfly Wing",
    "Blur Butterfly Wing": "Blue Butterfly Wing",
    "Blue Buterfly Wing": "Blue Butterfly Wing",
    "Blue Buttrefly Wing": "Blue Butterfly Wing",
    "Blue Butetrfly Wing": "Blue Butterfly Wing",
    "Blue Butterfly Wnig": "Blue Butterfly Wing",
    "Blu Butterly Wing": "Blue Butterfly Wing",
    "Blue Butterly Wing": "Blue Butterfly Wing",
    "Blue Butterfly Wign": "Blue Butterfly Wing",

    "Blu Dartwing": "Blue Dartwing",
    "Blur Dartwing": "Blue Dartwing",
    "Bleu Dartwing": "Blue Dartwing",
    "Bule Dartwing": "Blue Dartwing",
    "Blue Dratwing": "Blue Dartwing",
    "Blue Darwting": "Blue Dartwing",
    "Blue Dsrtwing": "Blue Dartwing",
    "Blue Dartwign": "Blue Dartwing",

    "Blur Mounatin FLower": "Blue Mountain Flower",
    "Blue Mountain Flwoer": "Blue Mountain Flower",
    "Blu Montain Flowre": "Blue Mountain Flower",
    "Blue Montain Flowre": "Blue Mountain Flower",
    "Blue Mountain Flowre": "Blue Mountain Flower",
    "Blue Moutnain Flower": "Blue Mountain Flower",

    "Bora Tusk": "Boar Tusk",
    "Blue Tusk": "Boar Tusk",
    "Broa Tusk": "Boar Tusk",
    "Brao Tusk": "Boar Tusk",
    "Obar Tusk": "Boar Tusk",
    "Boar Tsuk": "Boar Tusk",
    "Boar Tuks": "Boar Tusk",
    "Boar Utsk": "Boar Tusk",
    "Boart Usk": "Boar Tusk",

    "Bnoe Meal": "Bone Meal",
    "Boenm Eal": "Bone Meal",
    "Bone Mleal": "Bone Meal",
    "Boen Meal": "Bone Meal",
    "Bone Mela": "Bone Meal",
    "Bone Male": "Bone Meal",
    "Bone Mael": "Bone Meal",
    "Vone Meal": "Bone Meal",

    "Vriar Heart": "Briar Heart",
    "Brira Heart": "Briar Heart",
    "Brair Heart": "Briar Heart",
    "Briarh Eart": "Briar Heart",
    "Briar Hrate": "Briar Heart",
    "Briar Hesrt": "Briar Heart",
    "Briat Heart": "Briar Heart",
    "Brair Herat": "Briar Heart",

    "Burned Spriggan Wood": "Burnt Spriggan Wood",
    "Brunt Spriggan Wood": "Burnt Spriggan Wood",
    "Burtn Spriggan Wood": "Burnt Spriggan Wood",
    "Burnt Spirggan Wood": "Burnt Spriggan Wood",
    "Burnt Sprigang Wood": "Burnt Spriggan Wood",
    "Burnt Sprigan Wood": "Burnt Spriggan Wood",
    "Burnt Spirgang Wood": "Burnt Spriggan Wood",
    "Burnt Spriggand Wood": "Burnt Spriggan Wood",
    "Burnt Spriggan Wdoo": "Burnt Spriggan Wood",
    "Burnt Spriggan Rood": "Burnt Spriggan Wood",
    "Burn Spriggan Wood": "Burnt Spriggan Wood",

    "Buterfly Wing": "Butterfly Wing",
    "Buttrefly Wing": "Butterfly Wing",
    "Burttefly Wing": "Butterfly Wing",
    "Butterlfy Wing": "Butterfly Wing",
    "Butterlyf Wing": "Butterfly Wing",
    "Butetrfly Wing": "Butterfly Wing",
    "Butterfly Wnig": "Butterfly Wing",
    "Butterfly Wign": "Butterfly Wing",

    "Caenis Root": "Canis Root",
    "Cansi Root": "Canis Root",
    "Cnais Root": "Canis Root",
    "Cains Root": "Canis Root",
    "Canis Roto": "Canis Root",
    "Canis Rtoo": "Canis Root",

    "Chared Skeever Hide": "Charred Skeever Hide",
    "Cahhred Skeever Hide": "Charred Skeever Hide",
    "Cahrred Skeever Hide": "Charred Skeever Hide",
    "Charde Skkever Hide": "Charred Skeever Hide",
    "Charred Skkevver Hide": "Charred Skeever Hide",
    "Charred Skkever Hide": "Charred Skeever Hide",
    "Charred Skevver Hide": "Charred Skeever Hide",
    "Charred Skever Hide": "Charred Skeever Hide",
    "Charred Skeevre Hide": "Charred Skeever Hide",
    "Charred Skeever Ihde": "Charred Skeever Hide",
    "Charred Skeever Hdie": "Charred Skeever Hide",
    "Charred Sjeever Hide": "Charred Skeever Hide",

    "Charus Eggs": "Chaurus Eggs",
    "Chaus Eggs": "Chaurus Eggs",
    "Chaurus Egg": "Chaurus Eggs",
    "Chaurs Eggs": "Chaurus Eggs",
    "Chaurus Egsg": "Chaurus Eggs",
    "Cgaurus Eggs": "Chaurus Eggs",

    "Charus Hunter Antennae": "Chaurus Hunter Antennae",
    "Chaurs Hunter Antennae": "Chaurus Hunter Antennae",
    "Chaus Hunter Antenne": "Chaurus Hunter Antennae",
    "Chaurus Gunter Antennae": "Chaurus Hunter Antennae",
    "Chaurus Huntre Antennae": "Chaurus Hunter Antennae",
    "Cgaurus Hunter Antennae": "Chaurus Hunter Antennae",
    "Chaurus Hunter Atnennae": "Chaurus Hunter Antennae",
    "Chaurus Hunter Antenna": "Chaurus Hunter Antennae",
    "Chaurus Hunter Antnenae": "Chaurus Hunter Antennae",
    "Chaurus Hunter Antenn": "Chaurus Hunter Antennae",

    "Chicken Egg": "Chicken's Egg",
    "Chickens Egg": "Chicken's Egg",
    "Cjicken's Egg": "Chicken's Egg",
    "Chicken's Eggs": "Chicken's Egg",
    "Chicken Eggs": "Chicken's Egg",

    "Crepe Cluster": "Creep Cluster",
    "Cerpp Clusete": "Creep Cluster",
    "Creeo Clusetr": "Creep Cluster",
    "Creep Clusete": "Creep Cluster",
    "Crepe Clusetr": "Creep Cluster",
    "Creep Clusetr": "Creep Cluster",
    "Creeo Ckuster": "Creep Cluster",
    "Crepp Clusete": "Creep Cluster",
    "Crepp Clusetr": "Creep Cluster",
    "Creeo Clusetr": "Creep Cluster",
    "Creep Ckuster": "Creep Cluster",

    "Crinson Nirnort": "Crimson Nirnroot",
    "Crimson Nirnort": "Crimson Nirnroot",
    "Crmison Nirnroot": "Crimson Nirnroot",
    "Crimsno Nirnort": "Crimson Nirnroot",
    "Crimson Rnirnoot": "Crimson Nirnroot",
    "Crimson Nirnroor": "Crimson Nirnroot",
    "Crimosn Nirnoot": "Crimson Nirnroot",
    "Crimosn Nirnort": "Crimson Nirnroot",
    "Crimosn Nirnrot": "Crimson Nirnroot",
    "Crimson Nirnrot": "Crimson Nirnroot",
    "Crinson Nirnrot": "Crimson Nirnroot",

    "Cryodilic Spadetail": "Cyrodilic Spadetail",
    "Cyrodillic Spadetail": "Cyrodilic Spadetail",
    "Cryoildic Spadetail": "Cyrodilic Spadetail",
    "Cyroildic Spadetail": "Cyrodilic Spadetail",
    "Cryodillic Sapdetail": "Cyrodilic Spadetail",
    "Cyrodilic Sapdetail": "Cyrodilic Spadetail",
    "Cyrodillic Sapdetail": "Cyrodilic Spadetail",
    "Cryodilic Sapdetail": "Cyrodilic Spadetail",
    "Cyrodilic Apsdetail": "Cyrodilic Spadetail",
    "Cyrodilic Spadtail": "Cyrodilic Spadetail",
    "Cyrodilic Sdapetail": "Cyrodilic Spadetail",
    "Cyrodilic Spdetali": "Cyrodilic Spadetail",

    "Deadra Heart": "Daedra Heart",
    "Dadrea Heart": "Daedra Heart",
    "Daerda Heart": "Daedra Heart",
    "Daedra Haert": "Daedra Heart",
    "Daedra Hreat": "Daedra Heart",
    "Daedra Herat": "Daedra Heart",

    "Deabtheall": "Deathbell",
    "Deabthell": "Deathbell",
    "Daethbell": "Deathbell",
    "Deathblel": "Deathbell",
    "Detahbell": "Deathbell",
    "Dathebll": "Deathbell",
    "Dathbell": "Deathbell",
    "Dethball": "Deathbell",
    "Deathball": "Deathbell",

    "Dragons Tongue": "Dragon's Tongue",
    "Dargons Tongue": "Dragon's Tongue",
    "Dargon's Tongue": "Dragon's Tongue",
    "Draogn's Tongue": "Dragon's Tongue",
    "Dragon's Tonegu": "Dragon's Tongue",
    "Dragon's Tongeu": "Dragon's Tongue",
    "Draogn's Tonegu": "Dragon's Tongue",
    "Draogn's Tongeu": "Dragon's Tongue",
    "Fragon's Tongue": "Dragon's Tongue",
    "Dragon's Tone": "Dragon's Tongue",

    "Dwarevn Oil": "Dwarven Oil",
    "Dwemer Oil": "Dwarven Oil",
    "Drwaven Oil": "Dwarven Oil",
    "Drawven Oil": "Dwarven Oil",
    "Dwavren Oil": "Dwarven Oil",
    "Dwarven Oli": "Dwarven Oil",

    "Ectplasm": "Ectoplasm",
    "Etcoplasm": "Ectoplasm",
    "Ectoplasma": "Ectoplasm",
    "Ecotplasm": "Ectoplasm",
    "Wctorplasm": "Ectoplasm",
    "Wctoplasm": "Ectoplasm",
    "Ecotorplams": "Ectoplasm",
    "Ectorplams": "Ectoplasm",
    "Sctoplams": "Ectoplasm",
    "Sctoplasm": "Ectoplasm",
    "Sctorplasm": "Ectoplasm",

    "Elf's Ear": "Elves Ear",
    "Elve's Ear": "Elves Ear",
    "Elfs Ear": "Elves Ear",
    "Elisif Ear": "Elves Ear",
    "Elsv Ear": "Elves Ear",
    "Evles Ear": "Elves Ear",
    "Wvles Ear": "Elves Ear",
    "Else Fear": "Elves Ear",
    "Elves Ears": "Elves Ear",
    "Elf's Ears": "Elves Ear",

    "Empreor Parasol Moss": "Emperor Parasol Moss",
    "Emperor Prasaol Moss": "Emperor Parasol Moss",
    "Emperor Parasol Msos": "Emperor Parasol Moss",
    "Wmperor Pasarol Moss": "Emperor Parasol Moss",
    "Emperor Pasarol Moss": "Emperor Parasol Moss",
    "Empreor Pasarol Moss": "Emperor Parasol Moss",
    "Emperor Parosl Moss": "Emperor Parasol Moss",
    "Empreor Parosl Moss": "Emperor Parasol Moss",
    "Wmpeor Parosl Moss": "Emperor Parasol Moss",
    "Wmperor Parols Moss": "Emperor Parasol Moss",
    "Empeor Parosl Moss": "Emperor Parasol Moss",
    "Emperor Parasol": "Emperor Parasol Moss",
    "Parasol Moss": "Emperor Parasol Moss",
    "Emperor Moss": "Emperor Parasol Moss",
    "Emperor Parols Moss": "Emperor Parasol Moss",
    "Empreor Parols Moss": "Emperor Parasol Moss",
    "Wmpeor Parols Moss": "Emperor Parasol Moss",
    "Empeor Parols Moss": "Emperor Parasol Moss",

    "Eye Of Saber Cat": "Eye Of Sabre Cat",
    "Eyes Of Sabre Cat": "Eye Of Sabre Cat",
    "Eye Ofs Abre Cat": "Eye Of Sabre Cat",
    "Saber Cat Eye": "Eye Of Sabre Cat",
    "Sabre Cat Eye": "Eye Of Sabre Cat",
    "Saber Eye": "Eye Of Sabre Cat",
    "Sabre Eye": "Eye Of Sabre Cat",
    "Eye Of Sbaer Cat": "Eye Of Sabre Cat",
    "Eye Of Sabrec At": "Eye Of Sabre Cat",
    "Yee Of Sabre Cat": "Eye Of Sabre Cat",
    "Eyeo F Sabre Cat": "Eye Of Sabre Cat",

    "Flamer Ear": "Falmer Ear",
    "Falmre Ear": "Falmer Ear",
    "Falmers Ear": "Falmer Ear",
    "Farmer Ear": "Falmer Ear",
    "Falmer's Ear": "Falmer Ear",
    "Falmer Ears": "Falmer Ear",
    "Famler Ear": "Falmer Ear",
    "Falmer Era": "Falmer Ear",

    "Farengars Frost Salt": "Farengar's Frost Salt",
    "Fargenar's Frost Salt": "Farengar's Frost Salt",
    "Farengar's Frost Salts": "Farengar's Frost Salt",
    "Farengars Frost Salts": "Farengar's Frost Salt",

    "Felsad Tern Feathers": "Felsaad Tern Feathers",
    "Deldaad Tern Fdeathers": "Felsaad Tern Feathers",
    "Felsaad Tern Fdeathers": "Felsaad Tern Feathers",
    "Feslaad Tern Fdeathers": "Felsaad Tern Feathers",
    "Feslaad Tern Feathers": "Felsaad Tern Feathers",
    "Ffelsaad Tern Feathers": "Felsaad Tern Feathers",
    "Felsdaa Tern Feathers": "Felsaad Tern Feathers",
    "Felsaad Turn Feathers": "Felsaad Tern Feathers",
    "Delsaad Tern Feathers": "Felsaad Tern Feathers",
    "Fdelsaad Tern Feathers": "Felsaad Tern Feathers",
    "Fdelsaad Tern Fdeathers": "Felsaad Tern Feathers",
    "Deslaad Tern Feathers": "Felsaad Tern Feathers",
    "Delsaad Turn Feathers": "Felsaad Tern Feathers",

    "Finely Cut Void Salts": "Fine-Cut Void Salts",
    "Fine Cut Void Salt": "Fine-Cut Void Salts",
    "Fine-Cut Void Salt": "Fine-Cut Void Salts",
    "Finely Cut Void Salt": "Fine-Cut Void Salts",
    "Finely-Cut Void Salts": "Fine-Cut Void Salts",
    "Finely_Cut Void Salts": "Fine-Cut Void Salts",
    "Fine_Cut Void Salts": "Fine-Cut Void Salts",
    "Fine=Cut Void Salts": "Fine-Cut Void Salts",
    "Fine+Cut Void Salts": "Fine-Cut Void Salts",
    "Fine_Cut Void Salt": "Fine-Cut Void Salts",
    "Finely_Cut Void Salt": "Fine-Cut Void Salts",
    "Finley Cut Void Slats": "Fine-Cut Void Salts",
    "Fine Cut Void Slats": "Fine-Cut Void Salts",
    "Fine-Cut Void Slats": "Fine-Cut Void Salts",
    "Fine_Cut Void Slats": "Fine-Cut Void Salts",
    "Fine-Cut Void Slat": "Fine-Cut Void Salts",
    "Fine-Void Salts": "Fine-Cut Void Salts",
    "Fine Void Salts": "Fine-Cut Void Salts",
    "Fnie-Cut Void Salts": "Fine-Cut Void Salts",
    "Fnie Cut Void Salts": "Fine-Cut Void Salts",

    "Frie Salts": "Fire Salts",
    "Fire Slats": "Fire Salts",
    "Frie Slats": "Fire Salts",
    "Fire Salt": "Fire Salts",
    "Frie Salt:": "Fire Salts",
    "Frie Slat": "Fire Salts",

    "Fly Amanta": "Fly Amanita",
    "Fyl Amanita": "Fly Amanita",
    "Fly Amantina": "Fly Amanita",
    "Fly Anmanita": "Fly Amanita",
    "Fly Ananita": "Fly Amanita",
    "Fly Anamita": "Fly Amanita",
    "Fly Amnita": "Fly Amanita",
    "Flya Manita": "Fly Amanita",

    "Forst Mirriam": "Frost Mirriam",
    "Frots Mirriam": "Frost Mirriam",
    "Frost Miriam": "Frost Mirriam",
    "Forst Miriam": "Frost Mirriam",
    "Frots Miriam": "Frost Mirriam",
    "Frost Mririam": "Frost Mirriam",
    "Forst Mririam": "Frost Mirriam",
    "Frots Mririam": "Frost Mirriam",
    "Frost Mirram": "Frost Mirriam",
    "Forst Mirram": "Frost Mirriam",
    "Frots Mirram": "Frost Mirriam",
    "Frost Mirrima": "Frost Mirriam",
    "Forst Mirrima": "Frost Mirriam",
    "Frots Mirrima": "Frost Mirriam",
    "Frost Merriam": "Frost Mirriam",

    "Forst Salts": "Frost Salts",
    "Frosts Alts": "Frost Salts",
    "Forsts Alts": "Frost Salts",
    "Frost Slats": "Frost Salts",
    "Forst Slats": "Frost Salts",
    "Frost Salt": "Frost Salts",
    "Forst Salt": "Frost Salts",
    "Frots Salt": "Frost Salts",
    "Frost Slat": "Frost Salts",
    "Forst Slat": "Frost Salts",

    "Gralic": "Garlic",
    "Gaelic": "Garlic",
    "Garlick": "Garlic",
    "Garlik": "Garlic",
    "Garli": "Garlic",
    "Gralick": "Garlic",
    "Gralik": "Garlic",
    "Garlix": "Garlic",

    "Gigant L;ichen": "Giant Lichen",
    "Gigant Lichen": "Giant Lichen",
    "Giant L;ichen": "Giant Lichen",
    "Giant :ichen": "Giant Lichen",
    "Giantl Ichen": "Giant Lichen",
    "Giant Licehn": "Giant Lichen",
    "Ginat Lichen": "Giant Lichen",
    "Ginatl Ichen": "Giant Lichen",
    "Ginat Licehn": "Giant Lichen",
    "Giant Licjen": "Giant Lichen",
    "Giant Licken": "Giant Lichen",

    "Giants Toe": "Giant's Toe",
    "Giant Toe": "Giant's Toe",
    "Giant Toes": "Giant's Toe",
    "Gigant Toe": "Giant's Toe",
    "Giants Toes": "Giant's Toe",
    "Giant's Toes": "Giant's Toe",
    "Gigant's Toe": "Giant's Toe",
    "Gigants Toes": "Giant's Toe",
    "Ginats Toe": "Giant's Toe",
    "Ginat's Toe": "Giant's Toe",
    "Ginats Toes": "Giant's Toe",
    "Ginat's Toes": "Giant's Toe",

    "Glaemblossom": "Gleamblossom",
    "Gleam Blossom": "Gleamblossom",
    "Gleamb Lossom": "Gleamblossom",
    "Glemablossom": "Gleamblossom",
    "Gleamblsosom": "Gleamblossom",
    "Gleamblosom": "Gleamblossom",
    "Gleamblososm": "Gleamblossom",
    "Glemblsom": "Gleamblossom",
    "Glemblossom": "Gleamblossom",
    "Gleamblsom": "Gleamblossom",

    "Glowd Ust": "Glow Dust",
    "Glowdust": "Glow Dust",
    "Glowing Dust": "Glow Dust",
    "Glwo Dust": "Glow Dust",
    "Glow Dsut": "Glow Dust",

    "Golwing Mushrroms": "Glowing Mushrooms",
    "Glowing Myusherooms": "Glowing Mushrooms",
    "Golwing Mushrooms": "Glowing Mushrooms",
    "Glowingm Ushrooms": "Glowing Mushrooms",
    "Glwoing Mushrooms": "Glowing Mushrooms",
    "Glowing Mushrroms": "Glowing Mushrooms",
    "Golwing Myusherooms": "Glowing Mushrooms",
    "Glwoing Myusherooms": "Glowing Mushrooms",
    "Golwing Mushrroms": "Glowing Mushrooms",
    "Glwoing Mushrroms": "Glowing Mushrooms",
    "Gowing Mushrooms": "Glowing Mushrooms",

    "Rass Pod": "Grass Pod",
    "Ass Pod": "Grass Pod",
    "Garss Pod": "Grass Pod",
    "Pod Of Grass": "Grass Pod",
    "Grasp Od": "Grass Pod",
    "Grassp Od": "Grass Pod",

    "Hagrevan Claw": "Hagraven Claw",
    "Gagraven Claw": "Hagraven Claw",
    "Hargaven Claw": "Hagraven Claw",
    "Hagraven Vlaw": "Hagraven Claw",
    "Hagreven Vlaw": "Hagraven Claw",
    "Gargaven Vlaw": "Hagraven Claw",
    "Gargaven Claw": "Hagraven Claw",
    "Hargaven Vlaw": "Hagraven Claw",
    "Jagraven Calw": "Hagraven Claw",
    "Jagrevan Calw": "Hagraven Claw",
    "Hagraven Calw": "Hagraven Claw",
    "Hagrevan Vlaw": "Hagraven Claw",

    "Hagrevan Feathers": "Hagraven Feathers",
    "Jagraven Feathers": "Hagraven Feathers",
    "Gagraven Feathers": "Hagraven Feathers",
    "Hargaven Feathers": "Hagraven Feathers",
    "Hagraven Fdeathers": "Hagraven Feathers",
    "Jargaven Feathers": "Hagraven Feathers",
    "Jargaven Fdeathers": "Hagraven Feathers",
    "Hargaven Fdeathers": "Hagraven Feathers",
    "Gagraven Fdeathers": "Hagraven Feathers",
    "Gargaven Fdeathers": "Hagraven Feathers",

    "Hangingm Oss": "Hanging Moss",
    "Hagning Moss": "Hanging Moss",
    "Hagningm Oss": "Hanging Moss",
    "Hang Moss": "Hanging Moss",
    "Hnaging Moss": "Hanging Moss",
    "Hanging Msos": "Hanging Moss",

    "Hawkb Eak": "Hawk Beak",
    "Gawk Beak": "Hawk Beak",
    "Jawk Beak": "Hawk Beak",
    "Hwak Beak": "Hawk Beak",
    "Gwak Beak": "Hawk Beak",
    "Jwak Beak": "Hawk Beak",
    "Hwk Beak": "Hawk Beak",
    "Hawk Beka": "Hawk Beak",

    "Hwak Fdeathers": "Hawk Feathers",
    "Hawkf Eathers": "Hawk Feathers",
    "Jawk Feathers": "Hawk Feathers",
    "Gawk Feathers": "Hawk Feathers",
    "Hawk Deathers": "Hawk Feathers",
    "Hawk Fdeathers": "Hawk Feathers",
    "Hawkf Deathers": "Hawk Feathers",
    "Jawk Fdeahters": "Hawk Feathers",
    "Hawk Fdeahters": "Hawk Feathers",
    "Hawk Feahters": "Hawk Feathers",
    "Gawk Fdeathers": "Hawk Feathers",

    "Hawks Egg": "Hawk's Egg",
    "Hawk Egg": "Hawk's Egg",
    "Gawk's Egg": "Hawk's Egg",
    "Jawk's Egg": "Hawk's Egg",
    "Hwak Egg": "Hawk's Egg",
    "Hwak's Egg": "Hawk's Egg",
    "Jwak Egg": "Hawk's Egg",
    "Gawk Egg": "Hawk's Egg",
    "Hawk Eggs": "Hawk's Egg",
    "Hawk's Eggs": "Hawk's Egg",
    "Jawk Eggs": "Hawk's Egg",
    "Jawk's Eggs": "Hawk's Egg",
    "Gawk Eggs": "Hawk's Egg",
    "Gawk's Eggs": "Hawk's Egg",

    "Hsitcarp": "Histcarp",
    "Histcrap": "Histcarp",
    "Hist Carp": "Histcarp",
    "Histc Arp": "Histcarp",
    "Gistcarp": "Histcarp",
    "Jistcarp": "Histcarp",
    "Gistcrap": "Histcarp",
    "Jistcrap": "Histcarp",
    "Hitscarp": "Histcarp",
    "Hitscrap": "Histcarp",

    "Hneycomb": "Honeycomb",
    "Honecomb": "Honeycomb",
    "Honey Comb": "Honeycomb",
    "Moneycomb": "Honeycomb",
    "Goneycomb": "Honeycomb",
    "Goney Comb": "Honeycomb",
    "Joneycomb": "Honeycomb",
    "Joney Comb": "Honeycomb",
    "Honeycombe": "Honeycomb",
    "Goneycombe": "Honeycomb",
    "Joneycombe": "Honeycomb",

    "Humn Flesh": "Human Flesh",
    "Hunam Flehs": "Human Flesh",
    "Human Flehs": "Human Flesh",
    "Huamn Flesh": "Human Flesh",
    "Huamn Flehs": "Human Flesh",
    "Guman Flesh": "Human Flesh",
    "Juman Flesh": "Human Flesh",
    "Humanf Lesh": "Human Flesh",

    "Humn Heart": "Human Heart",
    "Human Haert": "Human Heart",
    "Humanh Eart": "Human Heart",
    "Human Hearth": "Human Heart",
    "Huamn Heart": "Human Heart",
    "Juman Heart": "Human Heart",
    "Human Jeart": "Human Heart",
    "Guman Heart": "Human Heart",
    "Human Geart": "Human Heart",
    "Juman Haert": "Human Heart",
    "Guman Haert": "Human Heart",
    "Humanh Aert": "Human Heart",

    "Ice Wraith Tooth": "Ice Wraith Teeth",
    "Ice Raith Teeth": "Ice Wraith Teeth",
    "Teeth Of Ice Wraith": "Ice Wraith Teeth",
    "Tooth Of Ice Wraith": "Ice Wraith Teeth",
    "Icew Raith Teeth": "Ice Wraith Teeth",
    "Ice Wriath Teeth": "Ice Wraith Teeth",
    "Ice Wraitht Eeth": "Ice Wraith Teeth",

    "Ipm Stool": "Imp Stool",
    "Imps Tool": "Imp Stool",
    "Imp Sotol": "Imp Stool",
    "Imp Stolo": "Imp Stool",

    "Hazbay Grapes": "Jazbay Grapes",
    "Jaxbay Grapes": "Jazbay Grapes",
    "Jazbay Grapse": "Jazbay Grapes",
    "Jaz Bay Grapes": "Jazbay Grapes",
    "Jacbay Grapes": "Jazbay Grapes",
    "Jazb Ay Grapes": "Jazbay Grapes",
    "Jazzbay Grapes": "Jazbay Grapes",
    "Jazbay Grasp": "Jazbay Grapes",
    "Jaxbay Grapse": "Jazbay Grapes",
    "Jacbay Grapse": "Jazbay Grapes",
    "Jaz Bay Grapse": "Jazbay Grapes",
    "Hazbay Grapse": "Jazbay Grapes",

    "Junipre Berries": "Juniper Berries",
    "Junieper Berries": "Juniper Berries",
    "Juneper Berries": "Juniper Berries",
    "Junpire Berries": "Juniper Berries",
    "Jupiner Berries": "Juniper Berries",
    "Junpier Berries": "Juniper Berries",
    "Juniper Beries": "Juniper Berries",
    "Jumiper Berreis": "Juniper Berries",
    "Juniper Berreis": "Juniper Berries",

    "Largea Ntlers": "Large Antlers",
    "Lagre Antlers": "Large Antlers",
    "Larg Eantlers": "Large Antlers",
    "Lgare Antlers": "Large Antlers",
    "Large Anlters": "Large Antlers",
    "Large Antles": "Large Antlers",

    "Lavnder": "Lavender",
    "Lavendre": "Lavender",
    "Lacender": "Lavender",
    "Labender": "Lavender",
    "Lavneder": "Lavender",

    "Luna Mth Wing": "Luna Moth Wing",
    "Lna Moth Wing": "Luna Moth Wing",
    "Luna Moth Wign": "Luna Moth Wing",
    "Lnua Moth Wing": "Luna Moth Wing",
    "Lua Moth Wing": "Luna Moth Wing",
    "Lunam Oth Wing": "Luna Moth Wing",
    "Luna Mothw Ing": "Luna Moth Wing",

    "Moons Sugar": "Moon Sugar",
    "Moon Suagr": "Moon Sugar",
    "Moons Ugar": "Moon Sugar",
    "Mono Sugar": "Moon Sugar",
    "Noon Sugar": "Moon Sugar",
    "Mon Sugar": "Moon Sugar",
    "Mnoo Sugar": "Moon Sugar",
    "Moon Sugars": "Moon Sugar",

    "Maro Tapinella": "Mora Tapinella",
    "Mora Topinella": "Mora Tapinella",
    "Mora Tapinalle": "Mora Tapinella",
    "Morat Apinella": "Mora Tapinella",
    "Mroa Tapinella": "Mora Tapinella",
    "Mora Tanipella": "Mora Tapinella",
    "Mora Tapinela": "Mora Tapinella",
    "Mora Tapniealla": "Mora Tapinella",
    "Mora Tapniella": "Mora Tapinella",

    "Mucdrab Chitin": "Mudcrab Chitin",
    "Mudcarb Chitin": "Mudcrab Chitin",
    "Mudcrabc Hitin": "Mudcrab Chitin",
    "Mucrab Chitin": "Mudcrab Chitin",
    "Nudcrab Chitin": "Mudcrab Chitin",
    "Mudcrab Chtiin": "Mudcrab Chitin",
    "Mudcrab Chtin": "Mudcrab Chitin",

    "Namiras Rot": "Namira's Rot",
    "Manira's Rot": "Namira's Rot",
    "Namira Rot": "Namira's Rot",
    "Mamira's Rot": "Namira's Rot",
    "Nanira's Rot": "Namira's Rot",
    "Mamiras Rot": "Namira's Rot",
    "Naniras Rot": "Namira's Rot",
    "Mamira Rot": "Namira's Rot",
    "Nanira Rot": "Namira's Rot",
    "Nmaria's Rot": "Namira's Rot",
    "Narmia's Rot": "Namira's Rot",
    "Namrias Rot": "Namira's Rot",

    "Neth Chelly": "Netch Jelly",
    "Neth Jelly": "Netch Jelly",
    "Nech Jelly": "Netch Jelly",
    "Netch Helly": "Netch Jelly",
    "Netchj Elly": "Netch Jelly",
    "Netc Hjelly": "Netch Jelly",
    "Ntech Jelly": "Netch Jelly",

    "Nighthshade": "Nightshade",
    "Nihgtshade": "Nightshade",
    "Nigthshade": "Nightshade",
    "Nightsahde": "Nightshade",
    "Nigtshade": "Nightshade",
    "Nihtshade": "Nightshade",

    "Ninort": "Nirnroot",
    "Nrinroot": "Nirnroot",
    "Nirnort": "Nirnroot",
    "Mirnorrt": "Nirnroot",
    "Nirnorrt": "Nirnroot",
    "Nirnrot": "Nirnroot",
    "Mirnroot": "Nirnroot",
    "Mrinroot": "Nirnroot",
    "Mirnort": "Nirnroot",

    "Nrdic Barnacle": "Nordic Barnacle",
    "Nodic Barnacle": "Nordic Barnacle",
    "Nodric Barnacle": "Nordic Barnacle",
    "Nordicb Arnacle": "Nordic Barnacle",
    "Nordc Barnacle": "Nordic Barnacle",
    "Nordic Barncle": "Nordic Barnacle",
    "Nordic Barncale": "Nordic Barnacle",

    "Orange Dratwing": "Orange Dartwing",
    "Range Dartwing": "Orange Dartwing",
    "Roange Dartwing": "Orange Dartwing",
    "Organge Dartwing": "Orange Dartwing",
    "Range Dratwing": "Orange Dartwing",
    "Roange Dratwing": "Orange Dartwing",
    "Organge Dratwing": "Orange Dartwing",
    "Oragne Dartwing": "Orange Dartwing",
    "Oragne Drawting": "Orange Dartwing",
    "Oragne Dratwing": "Orange Dartwing",
    "Orange Drawting": "Orange Dartwing",
    "Orange Drawing": "Orange Dartwing",
    "Oranged Artwing": "Orange Dartwing",

    "Paerl": "Pearl",
    "Preal": "Pearl",
    "Perl": "Pearl",
    "Peeal": "Pearl",
    "Peasl": "Pearl",

    "Pien Thrush Egg": "Pine Thrush Egg",
    "Pinet Hrush Egg": "Pine Thrush Egg",
    "Pine Thrushe Gg": "Pine Thrush Egg",
    "Pne Thrush Egg": "Pine Thrush Egg",
    "Pine Thush Egg": "Pine Thrush Egg",
    "Pine Thrudh Egg": "Pine Thrush Egg",
    "Pine Thursh Egg": "Pine Thrush Egg",

    "Poisonbloom": "Poison Bloom",
    "Poison Bllom": "Poison Bloom",
    "Posion Bloom": "Poison Bloom",
    "Posion Bllom": "Poison Bloom",
    "Posionbloom": "Poison Bloom",
    "Poision Bloom": "Poison Bloom",
    "Poision Bllom": "Poison Bloom",
    "Poisn Bloom": "Poison Bloom",

    "Powder Mammoth Tusk": "Powdered Mammoth Tusk",
    "Podwerd Mammoth Tusk": "Powdered Mammoth Tusk",
    "Pwodered Mammoth Tusk": "Powdered Mammoth Tusk",
    "Powderd Mammoth Tusk": "Powdered Mammoth Tusk",
    "Powdred Mammoth Tusk": "Powdered Mammoth Tusk",
    "Powdered Mamoth Tusk": "Powdered Mammoth Tusk",
    "Powdered Mamomth Tusk": "Powdered Mammoth Tusk",
    "Powdered Mammoth Tuks": "Powdered Mammoth Tusk",

    "Purpl Mountain Flower": "Purple Mountain Flower",
    "Purpel Mountain Flower": "Purple Mountain Flower",
    "Purple Montain Flower": "Purple Mountain Flower",
    "Purple Montian Flower": "Purple Mountain Flower",
    "Purpie Mountain Flwoer": "Purple Mountain Flower",
    "Purple Mountain Flwoer": "Purple Mountain Flower",
    "Purpel Mountain Flwoer": "Purple Mountain Flower",
    "Purpie Mountain Flower": "Purple Mountain Flower",
    "Purple Montain Flwoer": "Purple Mountain Flower",
    "Purple Montian Flwoer": "Purple Mountain Flower",
    "Purpl Montain Flwoer": "Purple Mountain Flower",
    "Purpl Montian Flwoer": "Purple Mountain Flower",

    "Red Montain Flower": "Red Mountain Flower",
    "Red Mintain Flower": "Red Mountain Flower",
    "Red Montian Flower": "Red Mountain Flower",
    "Red Mountain Flwoer": "Red Mountain Flower",
    "Red Mintain Flwoer": "Red Mountain Flower",
    "Red Montian Flwoer": "Red Mountain Flower",
    "Red Montain Flwoer": "Red Mountain Flower",

    "Rivre Betty": "River Betty",
    "Riverb Etty": "River Betty",
    "Rievre Betty": "River Betty",
    "River Btty": "River Betty",
    "River Beety": "River Betty",
    "Rtiver Betty": "River Betty",
    "River Bteey": "River Betty",

    "Rock Warberl Egg": "Rock Warbler Egg",
    "Rokc Warbler Egg": "Rock Warbler Egg",
    "Rcok Warbler Egg": "Rock Warbler Egg",
    "Rock Wrbler Egg": "Rock Warbler Egg",
    "Rockw Arbler Egg": "Rock Warbler Egg",
    "Rock Warbker Egg": "Rock Warbler Egg",
    "Rock Warblere Gg": "Rock Warbler Egg",

    "Saber Cat Tooth": "Sabre Cat Tooth",
    "Sarbe Cat Tooth": "Sabre Cat Tooth",
    "Asbre Cat Tooth": "Sabre Cat Tooth",
    "Sabre Cat's Tooth": "Sabre Cat Tooth",
    "Sabrec At Tooth": "Sabre Cat Tooth",
    "Sabre Catt Ooth": "Sabre Cat Tooth",

    "Salmn Roe": "Salmon Roe",
    "Salmon Row": "Salmon Roe",
    "Salmonr Oe": "Salmon Roe",
    "Slamon Roe": "Salmon Roe",
    "Sakmon Roe": "Salmon Roe",
    "Salmon Eoe": "Salmon Roe",

    "Slat Pile": "Salt Pile",
    "Salt Pilw": "Salt Pile",
    "Aslt Pile": "Salt Pile",
    "Salr Pile": "Salt Pile",
    "Saltp Ile": "Salt Pile",
    "Salt Plie": "Salt Pile",
    "Salt Pike": "Salt Pile",

    "Scaky Pholiota": "Scaly Pholiota",
    "Scalt Pholiota": "Scaly Pholiota",
    "Scalyp Holiota": "Scaly Pholiota",
    "Scaly Pholota": "Scaly Pholiota",
    "Csaly Pholiota": "Scaly Pholiota",
    "Scaly Pholioyta": "Scaly Pholiota",

    "Scathecraq": "Scathecraw",
    "Sxathecraw": "Scathecraw",
    "Scathexraw": "Scathecraw",
    "Scathercaw": "Scathecraw",
    "Scathcraw": "Scathecraw",

    "Silvreside Perch": "Silverside Perch",
    "Silverslide Perch": "Silverside Perch",
    "Sivlerside Perch": "Silverside Perch",
    "Silversidep Erch": "Silverside Perch",
    "Silversdie Perch": "Silverside Perch",
    "Sliverside Perch": "Silverside Perch",

    "Skevver Tail": "Skeever Tail",
    "Skkeever Tail": "Skeever Tail",
    "Skkevver Tail": "Skeever Tail",
    "Skeevre Tail": "Skeever Tail",
    "Skeevert Ail": "Skeever Tail",
    "Sleever Tail": "Skeever Tail",
    "Skeever Tali": "Skeever Tail",

    "Salughterfish Egg": "Slaughterfish Egg",
    "Slauhterfish Egg": "Slaughterfish Egg",
    "Slaughter Fish Egg": "Slaughterfish Egg",
    "Saulgtherfish Egg": "Slaughterfish Egg",
    "Slaguhtergish Egg": "Slaughterfish Egg",
    "Slaughtergish Egg": "Slaughterfish Egg",
    "Slaughterfishe Gg": "Slaughterfish Egg",
    "Salterfish Egg": "Slaughterfish Egg",
    "Slaughtefish Egg": "Slaughterfish Egg",

    "Slaughterfish Scalse": "Slaughterfish Scales",
    "Salughterfish Scales": "Slaughterfish Scales",
    "Slauhterfish Scales": "Slaughterfish Scales",
    "Slaughter Fish Scales": "Slaughterfish Scales",
    "Slaughterfish Sclaes": "Slaughterfish Scales",
    "Slaughterfish Scale": "Slaughterfish Scales",
    "Saulgtherfish Scales": "Slaughterfish Scales",
    "Slaguterfish Scales": "Slaughterfish Scales",
    "Slaughtergish Scales": "Slaughterfish Scales",
    "Salterfish Scales": "Slaughterfish Scales",
    "Slaughtefish Scales": "Slaughterfish Scales",

    "Smalla Ntlers": "Small Antlers",
    "Smlala Antlers": "Small Antlers",
    "Smlal Antlers": "Small Antlers",
    "Snall Antlers": "Small Antlers",
    "Small Amtlers": "Small Antlers",
    "Small Anterls": "Small Antlers",
    "Small Antler": "Small Antlers",

    "Small Perla": "Small Pearl",
    "Smlala Pearl": "Small Pearl",
    "Smlal Pearl": "Small Pearl",
    "Small Perl": "Small Pearl",
    "Snall Pearl": "Small Pearl",
    "Smallp Earl": "Small Pearl",
    "Small Preal": "Small Pearl",

    "Snow Berries": "Snowberries",
    "Snowberies": "Snowberries",
    "Snwoberries": "Snowberries",
    "Smowberries": "Snowberries",
    "Nowbreries": "Snowberries",
    "Snowbreries": "Snowberries",
    "Nowberries": "Snowberries",

    "Spwan Ash": "Spawn Ash",
    "Spawn Sah": "Spawn Ash",
    "Spawna Sh": "Spawn Ash",
    "Sawn Ash": "Spawn Ash",
    "Spawm Ash": "Spawn Ash",
    "Spawn Ahs": "Spawn Ash",

    "Spider's Egg": "Spider Egg",
    "Spider Eggs": "Spider Egg",
    "Spider's Eggs": "Spider Egg",
    "Spide Egg": "Spider Egg",
    "Spidre Egg": "Spider Egg",
    "Spidere Gg": "Spider Egg",
    "Sipder Egg": "Spider Egg",

    "Spirgan Sap": "Spriggan Sap",
    "Spirggan Sap": "Spriggan Sap",
    "Sprigan Sap": "Spriggan Sap",
    "Spriggans Ap": "Spriggan Sap",
    "Psriggan Sap": "Spriggan Sap",
    "Sprigang Sap": "Spriggan Sap",
    "Spriggn Sap": "Spriggan Sap",
    "Spriggan Spa": "Spriggan Sap",

    "Swap Fungal Pod": "Swamp Fungal Pod",
    "Swampf Ungal Pod": "Swamp Fungal Pod",
    "Swamp Fungalp Od": "Swamp Fungal Pod",
    "Smwap Funagl Pod": "Swamp Fungal Pod",
    "Swamp Funagl Pod": "Swamp Fungal Pod",
    "Swamp Fungl Pod": "Swamp Fungal Pod",
    "Swamp Fungal Pood": "Swamp Fungal Pod",
    "Swamp Gungal Pod": "Swamp Fungal Pod",
    "Swamp Gunfal Pod": "Swamp Fungal Pod",

    "Aproot": "Taproot",
    "Taport": "Taproot",
    "Taprot": "Taproot",
    "Taprrot": "Taproot",
    "Tapoort": "Taproot",

    "Thisle Branch": "Thistle Branch",
    "Thitle Barnch": "Thistle Branch",
    "Thistle Barnch": "Thistle Branch",
    "Thisle Barnch": "Thistle Branch",
    "Thitsle Branch": "Thistle Branch",
    "Thistleb Ranch": "Thistle Branch",

    "Torcgbug Thorax": "Torchbug Thorax",
    "Torthbug Thorax": "Torchbug Thorax",
    "Thorchbug Thorax": "Torchbug Thorax",
    "Torch Bug Thorax": "Torchbug Thorax",
    "Torchbug's Thorax": "Torchbug Thorax",
    "Borchtug Thorax": "Torchbug Thorax",
    "Torchbuh Thorax": "Torchbug Thorax",
    "Torchbug Thrax": "Torchbug Thorax",
    "Torchbug Thorac": "Torchbug Thorax",

    "Trana Root": "Trama Root",
    "Tarma Root": "Trama Root",
    "Trama Troo": "Trama Root",
    "Trma Root": "Trama Root",
    "Tramar Oot": "Trama Root",
    "Trama Rrot": "Trama Root",
    "Tram Root": "Trama Root",

    "Trollf At": "Troll Fat",
    "Rtoll Fat": "Troll Fat",
    "Trlol Fat": "Troll Fat",
    "Trolk Fat": "Troll Fat",
    "Trool Fat": "Troll Fat",
    "Troll Aft": "Troll Fat",

    "Tundr Cotton": "Tundra Cotton",
    "Undra Cotton": "Tundra Cotton",
    "Tunfra Cotton": "Tundra Cotton",
    "Tundra Coton": "Tundra Cotton",
    "Tundra's Cotton": "Tundra Cotton",
    "Tiundra Cotton": "Tundra Cotton",
    "Tudnra Cotton": "Tundra Cotton",
    "Tundra Cotoon": "Tundra Cotton",

    "Vamprie Dust": "Vampire Dust",
    "Vampite Dust": "Vampire Dust",
    "Vanpire Dust": "Vampire Dust",
    "Vampired Ust": "Vampire Dust",
    "Vampier Dust": "Vampire Dust",
    "Vampirer Dust": "Vampire Dust",

    "Voipd Salts": "Void Salts",
    "Void Salt": "Void Salts",
    "Vpid Salts": "Void Salts",
    "Void's Salts": "Void Salts",
    "Void's Salt": "Void Salts",
    "Coid Salts": "Void Salts",
    "Void Sakts": "Void Salts",
    "Void Slats": "Void Salts",

    "Wheta": "Wheat",
    "Hweat": "Wheat",
    "Qheat": "Wheat",

    "Whitec Ap": "White Cap",
    "Whte Cap":  "White Cap",
    "White Apc":  "White Cap",
    "Whtie Cap":  "White Cap",
    "Whitecap":  "White Cap",

    "Whisp Wrappings": "Wisp Wrappings",
    "Wisp's Wrappings":  "Wisp Wrappings",
    "Wisp Wrapping":  "Wisp Wrappings",
    "Wips Wrappings":  "Wisp Wrappings",
    "Wisp Warrpings":  "Wisp Wrappings",
    "Wisp Wrarpings":  "Wisp Wrappings",
    "Wisp Rwappings":  "Wisp Wrappings",

    "Yellw Mountian Flower": "Yellow Mountain Flower",
    "Yellow Mounatin Flower": "Yellow Mountain Flower",
    "Yellow Mountian Flower": "Yellow Mountain Flower",
    "Yellow Mountain Flwoer":  "Yellow Mountain Flower",
    "Yellw Mounatin Flower":  "Yellow Mountain Flower",
    "Yellw Mounatin Flwoer":  "Yellow Mountain Flower",
    "Yellow Mounatin Flwoer":  "Yellow Mountain Flower",
    "Yellow Mountian Flwoer":  "Yellow Mountain Flower",
    "Yellowm Ountain Flower":  "Yellow Mountain Flower",
    "Yellow Mountainf Lower":  "Yellow Mountain Flower",
    "Yellw Mountain Flower":  "Yellow Mountain Flower"
}